import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/layout/navbar";
import Hero from "@/components/sections/Hero";
import ClientSlide from "@/components/ui/SliderClient";
import About from "@/components/sections/About";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>3D Assets Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen bg-black text-white font-sans  overflow-x-hidden">
        <Navbar />
        <Hero />
        <About />
        {/* <ClientSlide /> */}
        <ClientSlide />
      </main>
    </>
  );
}
